FindNearestChangingTableVersion1/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FindNearestChangingTableVersion1.Data;
using FindNearestChangingTableVersion1.Models;
using FindNearestChangingTableVersion1.Models.MapViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FindNearestChangingTableVersion1.Controllers
{
    public class MapController : Controller
    {
        private NewHorizonsDBContext context;
        private readonly UserManager<ApplicationUser> userManager;


        public MapController(NewHorizonsDBContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("Map/GetAllLocations")]
        public JsonResult GetAllLocations()
        {
            List<AddLocationToMapViewModel> allLocations = AddLocationToMapViewModel.GetAllLocations(context);
            return new JsonResult(allLocations);
        }

        [HttpGet]
        [Authorize]
        [Route("Map/AddLocationToMap/{name}/{address}/{hours}/{description}/{latlng}")]
        public bool AddLocationToMap(string name, string address, string hours, string description, string latlng)
        {
            string userId = userManager.GetUserId(User);
            AddLocationToMapViewModel newLocation = new AddLocationToMapViewModel()
            {
                UserId = userId,
                Name = name,
                Address = address,
                Hours = hours,
                Description = description,
                LatLng = latlng,
            };

            return newLocation.AddLocationToMap(context);
        }

        [HttpGet]
        [Route("Map/NearestLocations")]
        public IActionResult NearestLocations()
        {
            return View();
        }

        [HttpGet]
        [Route("Map/FindNearestLocations")]
        public JsonResult FindNearestLocations()
        {
            List<AddLocationToMapViewModel> allLocations = AddLocationToMapViewModel.GetAllLocations(context);
            return new JsonResult(allLocations);
        }

        [HttpGet]
        [Route("Map/ShowNearestLocation/{name}/{address}/{hours}/{description}/{position}")]
        public IActionResult ShowNearestLocation(string name, string address, string hours, string description, string position)
        {
            AddLocationToMapViewModel nearestLocation = new AddLocationToMapViewModel()
            {
                Name = name,
                Address = address,
                Hours = hours,
                Description = description,
                LatLng = position,
            };
            return View(nearestLocation);
        }

    }
}

FindNearestChangingTableVersion1/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FindNearestChangingTableVersion1.Data;
using FindNearestChangingTableVersion1.Models;
using FindNearestChangingTableVersion1.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FindNearestChangingTableVersion1.Controllers
{
    public class UserController : Controller
    {
        private NewHorizonsDBContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public UserController(NewHorizonsDBContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public IActionResult EditLocation()
        {
            string userID = userManager.GetUserId(User);
            List<EditLocationViewModel> locationList = EditLocationViewModel.DisplayList(context, userID);
            if (locationList == null)
                ViewData["Message"] = "Du har inte lagt till några skötbord";
            return View(locationList);
        }
        [Route("User/Delete/{id}")]
        [HttpGet]
        public JsonResult Delete(int id)
        {
            bool locationDeleted = EditLocationViewModel.DeleteMarker(context, id);
            return new JsonResult(locationDeleted);
        }
        [Route("User/Update/{locID}/{newName}/{newAdress}/{newHours}/{newDescription}")]
        [HttpGet]
        public JsonResult Update(int locID, string newName, string newAdress, string newHours, string newDescription)
        {
            EditLocationViewModel model = new EditLocationViewModel()
            { ID = locID, Name = newName, Adress = newAdress, Hours = newHours, Description = newDescription};
            bool locationUpdated = EditLocationViewModel.UpdateMarker(context, model);

            return new JsonResult(locationUpdated);
        }
    }
}

FindNearestChangingTableVersion1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sköt dig själv</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav style="height: 70px;background-color:#119979" class="navbar navbar-inverse navbar-fixed-top"> @*(grå färg 7e9988)*@
        <div class="container" style="background-color:#119979">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Map" asp-action="Index" class="navbar-brand">
                    <img style="max-width:230px; margin-top: -70px; margin-left:20px"; src="~/images/SkötbordLogoNamn.png" /> 
                </a>
            </div>
            <div class="navbar-collapse collapse" >
                <ul class="nav navbar-nav"style="margin-top: 18px;">
                    <li><a asp-area="" asp-controller="Map" asp-action="NearestLocations" style="color:black; font-size:large; font-weight:bold;">Närmast dig</a></li>
                    @if(User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="EditLocation" style="color:black; font-size:large; font-weight:bold;">Dina platser</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact" style="color:black; font-size:large; font-weight:bold;">Kontakt</a></li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-area="" asp-controller="Admin" asp-action="AdminIndex" style="color:black;font-size:large; font-weight:bold;">Admin</a>
                            }
                        }
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Sköt dig själv</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>